version: "3.3"
services:
  nginx:
    depends_on:
      - react_client
      - api_backend
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/opt/certs/:/etc/ssl/private

  react_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    #ports:
    #  - '3000:3000'
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    restart: on-failure
    container_name: React_client
  api_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #  - '3001:3001'
    restart: on-failure
    container_name: api_backend
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    env_file:
      - ./env/backend.env


  letsencrypt:
    image: linuxserver/swag
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=aziostore.tk
      - SUBDOMAINS=wildcard,
      - VALIDATION=dns
      - DNSPLUGIN=route53
      - EMAIL=irahulsah306@gmail.com
      - DHLEVEL=4096
    volumes:
      - ./config/opt/:/config
    restart: unless-stopped
  mongo:
    container_name: mongo-db-demo
    image: mongo
    ports:
      - '27017:27017'
    
    volumes: 
      - mongo-data:/data/db
volumes:
    mongo-data:
      driver: local
    
